/**
 * All user-facing copy lives here so the app can be translated
 * without touching components (i18n-ready, English is the shipped locale).
 */
export const t = {
  appName: 'Debrief',
  appTagline: 'Visit feedback in under a minute',

  login: {
    title: 'Sign in',
    subtitle: 'Use your agency account.',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    invalid: 'Email or password is incorrect.',
    hint: 'Demo accounts: marie.laurent@demo.agency, koen.devos@demo.agency, admin@demo.agency — password demo1234',
  },

  nav: {
    signOut: 'Sign out',
    admin: 'Network view',
    myVisits: 'My visits',
    criteria: 'Feedback fields',
    people: 'Agents',
    viewings: 'Viewings',
    settings: 'Settings',
    account: 'My account',
    back: 'Back',
  },

  account: {
    title: 'My account',
    subtitle: 'Change the password used to sign in.',
    current: 'Current password',
    next: 'New password',
    confirm: 'Repeat new password',
    submit: 'Change password',
    changed: 'Password changed.',
    wrongCurrent: 'Current password is incorrect.',
    mismatch: 'The two new passwords do not match.',
    tooShort: 'Use at least 8 characters.',
  },

  criteria: {
    title: 'Feedback fields',
    subtitle: 'What the AI fills in from a dictation. Three to six works best.',
    label: 'Field name',
    hint: 'Description (optional)',
    hintHelp: 'Shown to the agent under "Points to cover" and used by the AI to decide what belongs here.',
    type: 'Answer type',
    typeText: 'Free text',
    typeRating: 'Rating',
    typeChoice: 'Choice from a list',
    ratingMax: 'Highest rating',
    options: 'Options (one per line)',
    key: 'Key sent to the endpoint',
    keyLocked: 'Fixed once created, because submitted feedback refers to it.',
    active: 'Active',
    save: 'Save',
    add: 'Add field',
    addTitle: 'New field',
    deactivate: 'Deactivate',
    activate: 'Activate',
    inactive: 'Inactive',
    empty: 'No fields configured yet.',
    needsOptions: 'Add at least two options for a choice field.',
    order: 'Order',
    moveUp: 'Move up',
    moveDown: 'Move down',
  },

  people: {
    title: 'Agents',
    subtitle: 'Who can sign in, and which branch they belong to.',
    name: 'Name',
    email: 'Email',
    branch: 'Branch',
    role: 'Role',
    roleAgent: 'Agent',
    roleAdmin: 'Administrator',
    zohoId: 'Zoho user id (optional)',
    tempPassword: 'Temporary password',
    tempPasswordHelp: 'Give this to the person for their first sign-in; they change it under My account.',
    add: 'Add person',
    addTitle: 'New person',
    resetPassword: 'Reset password',
    created: (email: string, password: string) => `${email} created. Temporary password: ${password}`,
    reset: (email: string, password: string) => `Password for ${email} reset to: ${password}`,
    emailTaken: 'That email already has an account.',
    visitsCount: (n: number) => `${n} viewings`,
  },

  viewings: {
    title: 'Viewings',
    subtitle: 'In production these arrive from Zoho. Here you can assign them by hand.',
    assignTo: 'Agent',
    address: 'Property address',
    prospect: 'Prospect name',
    propertyRef: 'Property reference',
    when: 'Date and time',
    add: 'Assign viewing',
    addTitle: 'New viewing',
    cancel: 'Cancel viewing',
    cancelled: 'Cancelled',
    reopen: 'Reopen',
    created: 'Viewing assigned.',
    hoursAgoHelp: 'Set a time in the past for a viewing that already needs feedback.',
  },

  settings: {
    title: 'Settings',
    subtitle: 'Behaviour the agency controls without a release.',
    language: 'Language of the filled fields',
    languageHelp: 'The verbatim always stays in the language the agent spoke.',
    reminders: 'Reminder signals',
    remindersHelp: 'The agency sends the reminders; the app signals when they are due.',
    firstReminder: 'First reminder after (hours)',
    secondReminder: 'Second reminder after (hours)',
    expiry: 'Expire after (days)',
    webhook: 'Outbound webhook',
    webhookUrl: 'Webhook URL',
    webhookToken: 'Webhook bearer token',
    webhookHelp: 'Left empty, events are still recorded so the contract can be reviewed.',
    zohoFilter: 'Zoho viewing filter',
    zohoFilterHelp: 'The event type treated as a property viewing. Configurable, never hard-coded.',
    save: 'Save settings',
    saved: 'Settings saved.',
    runStateCheck: 'Run state check now',
    stateCheckResult: (d: number, r: number, e: number) =>
      `State check done: ${d} due, ${r} reminders, ${e} expired.`,
  },

  summary: {
    title: 'Submitted feedback',
    agentTitle: 'What you submitted',
    delivery: 'Delivery to the endpoint',
    submittedAt: (when: string) => `Submitted ${when}`,
    attempts: (n: number) => `${n} attempts`,
    editedByAgent: 'Edited by the agent before submitting.',
    takesSummary: (takes: number, seconds: number) =>
      `${takes} recording${takes === 1 ? '' : 's'}, ${seconds}s of audio.`,
    showPayload: 'Show the payload sent to the endpoint',
    notSubmitted: 'This viewing has no submitted feedback.',
    draftInProgress: 'A draft is in progress — nothing has been submitted yet.',
  },

  zoho: {
    title: 'Zoho connection',
    subtitle: 'Read-only. The app never writes anything back into the CRM.',
    connection: 'Credentials',
    connectionHelp:
      'From a Self Client in the Zoho API console, with scope ZohoCRM.modules.READ, ZohoCRM.settings.READ, ZohoCRM.users.READ.',
    dataCenter: 'Data centre',
    clientId: 'Client ID',
    clientSecret: 'Client secret',
    refreshToken: 'Refresh token',
    secretKept: 'Stored. Leave as is to keep it, or type a new value.',
    test: 'Test connection',
    testing: 'Testing…',
    connected: (org: string, users: number) => `Connected to ${org} · ${users} active users`,
    notConnected: 'Not connected yet',
    mapping: 'What counts as a viewing',
    mappingHelp: 'Configurable, never hard-coded — the recognition rule can change without a release.',
    module: 'Module',
    filterField: 'Field to match on',
    filterValue: 'Value it must contain',
    fields: 'Field mapping',
    fieldAddress: 'Property address',
    fieldProspect: 'Prospect',
    fieldPropertyRef: 'Property reference',
    fieldStart: 'Start of the viewing',
    loadFields: 'Load fields from Zoho',
    fieldsLoaded: (n: number) => `${n} fields loaded — the inputs now suggest them.`,
    windowDays: 'Import viewings from the last (days)',
    save: 'Save connection',
    saved: 'Connection saved.',
    sync: 'Synchronise now',
    syncing: 'Synchronising…',
    lastSync: (when: string) => `Last synchronised ${when}`,
    neverSynced: 'Never synchronised',
    syncResult: (r: { fetched: number; matched: number; created: number; updated: number; cancelled: number; unassigned: number }) =>
      `${r.fetched} records read, ${r.matched} matched the rule, ${r.created} added, ${r.updated} updated, ${r.cancelled} cancelled, ${r.unassigned} without a matching agent.`,
    unassignedHelp:
      'A viewing is skipped when its Zoho owner matches no account here. Fill in the Zoho user id on the agent to link them.',
  },

  events: {
    title: 'Outbound events',
    subtitle: 'Every signal sent to the reminder engine, delivered or not.',
    empty: 'No events yet. Run the state check to generate them.',
    notConfigured: 'Recorded, no URL set',
    delivered: 'Delivered',
    failed: 'Failed',
  },

  visits: {
    title: 'My visits',
    todo: 'To do',
    done: 'Done',
    expired: 'Expired',
    emptyTodo: 'Nothing waiting for feedback. Well done.',
    emptyDone: 'No feedback submitted yet.',
    emptyExpired: 'No expired or cancelled viewings.',
    pendingFor: (h: string) => `Waiting ${h}`,
    cancelled: 'Cancelled in the calendar',
    answered: 'Feedback submitted',
    expiredNote: 'Deadline passed',
    draftChip: 'Draft',
  },

  feedback: {
    backToList: 'My visits',
    pointsToCover: 'Points to cover',
    recordCta: 'Hold the phone close and talk freely — the app sorts out what goes where.',
    startRecording: 'Record feedback',
    stopRecording: 'Stop',
    recording: 'Recording',
    playback: 'Play back',
    pause: 'Pause',
    redo: 'Record again',
    confirmRecording: 'Confirm my recording',
    processing: 'Transcribing and filling fields…',
    processingField: 'Filling this field…',
    fieldsFilled: 'Fields filled from your recording. Review and confirm.',
    incomplete: 'Incomplete, please complete',
    missing: 'Not mentioned, please complete',
    confirm: 'Confirm',
    confirmed: 'Confirmed',
    edit: 'Edit',
    saveEdit: 'Save',
    cancelEdit: 'Cancel',
    fieldMicHint: 'Add detail to this field only',
    generalFeedback: 'General feedback',
    verbatim: 'Your words, as recorded',
    verbatimNote: 'Stored in full, not editable.',
    takes: 'Recordings',
    take: (n: number) => `Take ${n}`,
    takeField: (n: number, label: string) => `Take ${n} · ${label} only`,
    addTake: 'Add another recording',
    addTakeHint: 'Each recording builds on the last one — say what you forgot.',
    updatedByTake: 'Updated by your last recording',
    ratingHint: (max: number) => `1 to ${max}`,
    chooseOption: 'Choose an option',
    confirmAll: 'Confirm all and submit',
    submitting: 'Saving your feedback…',
    submitted: 'Your feedback has been saved.',
    submitFailed: 'We could not save your feedback. It will be retried — nothing is lost.',
    analysisFailed: 'We could not process your recording. Try again.',
    retry: 'Try again',
    draftSaved: 'Draft saved',
    typeHere: 'Type or use the microphone…',
    micDenied: 'Microphone access is blocked. Allow it in your browser settings, or type instead.',
    backToVisits: 'Back to my visits',
    doneTitle: 'Feedback saved',
    doneBody: 'The viewing has moved to Done. You can close this page.',
  },

  admin: {
    title: 'Network view',
    subtitle: 'Response status across the pilot branches',
    agents: 'Agents',
    agent: 'Agent',
    branch: 'Branch',
    pending: 'Pending',
    answeredCol: 'Answered',
    responseRate: 'Response rate',
    visits: 'All viewings',
    visit: 'Viewing',
    prospect: 'Prospect',
    status: 'Status',
    waiting: 'Waiting',
    exportCsv: 'Export CSV',
    submissionErrors: 'Submission errors',
    noErrors: 'No failed submissions.',
    inbox: 'Endpoint deliveries',
    inboxNote: 'Payloads received by the agency endpoint (mocked in this demo).',
    resetDemo: 'Reset demo data',
    resetting: 'Resetting…',
    resetNote: 'Clears every draft and submission and restores the viewings, so the demo can be run again.',
  },

  status: {
    PENDING: 'Pending',
    REMINDER_SENT: 'Reminded',
    DRAFT: 'Draft',
    ANSWERED: 'Answered',
    EXPIRED: 'Expired',
    CANCELLED: 'Cancelled',
  } as Record<string, string>,
};
