/**
 * All user-facing copy lives here so the app can be translated
 * without touching components (i18n-ready, English is the shipped locale).
 */
export const t = {
  appName: 'Debrief',
  appTagline: 'Visit feedback in under a minute',

  login: {
    title: 'Sign in',
    subtitle: 'Use your agency account.',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    invalid: 'Email or password is incorrect.',
    hint: 'Demo accounts: marie.laurent@demo.agency, koen.devos@demo.agency, admin@demo.agency — password demo1234',
  },

  nav: {
    signOut: 'Sign out',
    admin: 'Network view',
    myVisits: 'My visits',
  },

  visits: {
    title: 'My visits',
    todo: 'To do',
    done: 'Done',
    expired: 'Expired',
    emptyTodo: 'Nothing waiting for feedback. Well done.',
    emptyDone: 'No feedback submitted yet.',
    emptyExpired: 'No expired or cancelled viewings.',
    pendingFor: (h: string) => `Waiting ${h}`,
    cancelled: 'Cancelled in the calendar',
    answered: 'Feedback submitted',
    expiredNote: 'Deadline passed',
    draftChip: 'Draft',
  },

  feedback: {
    backToList: 'My visits',
    pointsToCover: 'Points to cover',
    recordCta: 'Hold the phone close and talk freely — the app sorts out what goes where.',
    startRecording: 'Record feedback',
    stopRecording: 'Stop',
    recording: 'Recording',
    playback: 'Play back',
    pause: 'Pause',
    redo: 'Record again',
    confirmRecording: 'Confirm my recording',
    processing: 'Transcribing and filling fields…',
    processingField: 'Filling this field…',
    fieldsFilled: 'Fields filled from your recording. Review and confirm.',
    incomplete: 'Incomplete, please complete',
    missing: 'Not mentioned, please complete',
    confirm: 'Confirm',
    confirmed: 'Confirmed',
    edit: 'Edit',
    saveEdit: 'Save',
    cancelEdit: 'Cancel',
    fieldMicHint: 'Add detail to this field only',
    generalFeedback: 'General feedback',
    verbatim: 'Your words, as recorded',
    verbatimNote: 'Stored in full, not editable.',
    confirmAll: 'Confirm all and submit',
    submitting: 'Saving your feedback…',
    submitted: 'Your feedback has been saved.',
    submitFailed: 'We could not save your feedback. It will be retried — nothing is lost.',
    analysisFailed: 'We could not process your recording. Try again.',
    retry: 'Try again',
    draftSaved: 'Draft saved',
    typeHere: 'Type or use the microphone…',
    micDenied: 'Microphone access is blocked. Allow it in your browser settings, or type instead.',
    backToVisits: 'Back to my visits',
    doneTitle: 'Feedback saved',
    doneBody: 'The viewing has moved to Done. You can close this page.',
  },

  admin: {
    title: 'Network view',
    subtitle: 'Response status across the pilot branches',
    agents: 'Agents',
    agent: 'Agent',
    branch: 'Branch',
    pending: 'Pending',
    answeredCol: 'Answered',
    responseRate: 'Response rate',
    visits: 'All viewings',
    visit: 'Viewing',
    prospect: 'Prospect',
    status: 'Status',
    waiting: 'Waiting',
    exportCsv: 'Export CSV',
    submissionErrors: 'Submission errors',
    noErrors: 'No failed submissions.',
    inbox: 'Endpoint deliveries',
    inboxNote: 'Payloads received by the agency endpoint (mocked in this demo).',
  },

  status: {
    PENDING: 'Pending',
    DRAFT: 'Draft',
    ANSWERED: 'Answered',
    EXPIRED: 'Expired',
    CANCELLED: 'Cancelled',
  } as Record<string, string>,
};
